kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-demo
  namespace: kube-system
  labels:
    app: nodejs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-demo
  template:
    metadata:
      labels:
        app: nodejs-demo
    spec:
      containers:
      - name: nodejs
        image: "devopshint/nodejsdocker"
        
---
apiVersion: apps/v1
kind: Service
metadata:
  name: nodejs-demo
  namespace: kube-system
spec:
  selector:
    app: nodejs-demo
  ports:
  - name: http
    targetPort: 80
    port: 80
        
